<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RiveSkia</RootNamespace>
    <PackageId>RiveSkia.Avalonia</PackageId>
    <Version>0.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\native\rive_shim.dll"
          Pack="true"
          PackagePath="runtimes/win-x64/native/"
          CopyToOutputDirectory="PreserveNewest"
          Link="rive_shim.dll" />
  </ItemGroup>

</Project>